name: Renovate

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: Logging level
        required: true
        type: choice
        default: info
        options:
          - info
          - debug
  schedule:
    - cron: "15 8-22/6 * * *"

concurrency: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        owner:
          - ${{ github.repository_owner }}
          - openrunks

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Github Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.RENOVATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ matrix.owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        env:
          LOG_LEVEL: ${{ github.event.inputs.log_level }}
          RENOVATE_USERNAME: ${{ vars.RENOVATE_USERNAME }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_AUTODISCOVER_FILTER: ${{ matrix.owner }}/*
        with:
          configurationFile: .github/renovate-config.json5
          token: ${{ steps.app-token.outputs.token }}
